
CREATE TABLE attachment
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    attachment_url VARCHAR(255),
    draft_id       BIGINT,
    post_id        BIGINT,
    CONSTRAINT pk_attachment PRIMARY KEY (id)
);

CREATE TABLE comment
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    post_id             BIGINT,
    user_id             BIGINT                                  NOT NULL,
    text                VARCHAR(255),
    date                date                                    NOT NULL,
    previous_comment_id BIGINT,
    CONSTRAINT pk_comment PRIMARY KEY (id)
);

CREATE TABLE draft
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT,
    text    VARCHAR(255),
    CONSTRAINT pk_draft PRIMARY KEY (id)
);

CREATE TABLE post
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text    VARCHAR(255),
    user_id BIGINT,
    date    date                                    NOT NULL,
    CONSTRAINT pk_post PRIMARY KEY (id)
);

CREATE TABLE "user"
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(30),
    last_name  VARCHAR(30),
    username   VARCHAR(30),
    password   VARCHAR(255),
    bio        VARCHAR(1000),
    role       VARCHAR(255),
    CONSTRAINT pk_user PRIMARY KEY (id)
);

ALTER TABLE attachment
    ADD CONSTRAINT FK_ATTACHMENT_ON_DRAFT FOREIGN KEY (draft_id) REFERENCES draft (id);

ALTER TABLE attachment
    ADD CONSTRAINT FK_ATTACHMENT_ON_POST FOREIGN KEY (post_id) REFERENCES post (id);

ALTER TABLE comment
    ADD CONSTRAINT FK_COMMENT_ON_POST FOREIGN KEY (post_id) REFERENCES post (id);

ALTER TABLE comment
    ADD CONSTRAINT FK_COMMENT_ON_PREVIOUS_COMMENT FOREIGN KEY (previous_comment_id) REFERENCES comment (id);

ALTER TABLE comment
    ADD CONSTRAINT FK_COMMENT_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id);

ALTER TABLE draft
    ADD CONSTRAINT FK_DRAFT_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id);

ALTER TABLE post
    ADD CONSTRAINT FK_POST_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id);